import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { buildNatalPatternReading } from "@/lib/natalPatterns";
import { ArrowLeft, ArrowUpRight, BookOpen, LockKeyhole, Sparkles } from "lucide-react";
import React from "react";
import { Link } from "wouter";

function count(value: unknown) { return Array.isArray(value) ? value.length : 0; }
function localDateKey() { return new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }

function PageHeader() {
  return <header className="border-b border-[#102936]/10"><div className="mx-auto flex max-w-4xl items-center justify-between px-5 py-5"><Link href="/" className="flex items-center gap-3 font-mono text-[10px] tracking-[.14em]"><ArrowLeft size={14} /> COSMIC WISDOM</Link><span className="font-mono text-[9px] tracking-[.14em] text-[#B63C5E]">NATAL / PATTERN NOTES</span></div></header>;
}

export default function NatalDetails() {
  const { isAuthenticated, loading } = useAuth();
  const chart = trpc.cosmic.getNatalChart.useQuery(undefined, { enabled: isAuthenticated });
  const data = chart.data?.chartData as { planets?: unknown[]; houses?: unknown[]; aspects?: unknown[] } | undefined;
  const pattern = buildNatalPatternReading(chart.data?.chartData, localDateKey());

  if (loading) return <main className="flex min-h-screen items-center justify-center bg-[#F3F0E9] text-[#102936]"><p className="font-mono text-[10px] tracking-[.14em]">OPENING PRIVATE NOTES…</p></main>;
  if (!isAuthenticated) return <main className="min-h-screen bg-[#F3F0E9] text-[#102936]"><PageHeader /><section className="mx-auto max-w-4xl px-5 py-14"><p className="font-mono text-[10px] font-semibold tracking-[.16em] text-[#B63C5E]">CHART DETAILS</p><h1 className="mt-5 font-serif text-5xl leading-[.88] tracking-[-.06em] md:text-6xl">Your chart details<br /><em className="font-light text-[#B63C5E]">are private.</em></h1><div className="mt-10 max-w-xl border border-[#102936]/15 bg-white/60 p-7"><LockKeyhole className="text-[#B63C5E]" size={18} /><h2 className="mt-4 font-serif text-3xl">Sign in to continue.</h2><p className="mt-3 font-sans text-[14px] leading-6 text-[#55707d]">Use your local email account or connected account to see your own natal calculation notes.</p><Link href="/account" className="mt-6 inline-flex h-11 items-center bg-[#211B2A] px-5 font-mono text-[9px] tracking-[.14em] text-white hover:bg-[#EF5D3F]">OPEN PRIVATE ACCOUNT</Link></div></section></main>;
  if (chart.isLoading) return <main className="flex min-h-screen items-center justify-center bg-[#F3F0E9] text-[#102936]"><p className="font-mono text-[10px] tracking-[.14em]">READING YOUR PRIVATE PATTERN…</p></main>;

  return <main className="min-h-screen bg-[#F3F0E9] text-[#102936]"><PageHeader /><section className="mx-auto max-w-4xl px-5 py-14"><p className="font-mono text-[10px] font-semibold tracking-[.16em] text-[#B63C5E]">CHART DETAILS</p><h1 className="mt-5 font-serif text-5xl leading-[.88] tracking-[-.06em] md:text-6xl">See what your reading<br /><em className="font-light text-[#B63C5E]">is built from.</em></h1><p className="mt-6 max-w-2xl font-sans text-[16px] leading-7 text-[#55707d]">Cosmic keeps your chart private and turns your saved birth details into placements, houses, and aspects for reflective interpretation. This is a method note, not a prediction.</p>
    {chart.data ? <div className="mt-10 space-y-5"><div className="grid gap-4 sm:grid-cols-3">{[["PLACEMENTS", count(data?.planets)], ["HOUSES", count(data?.houses)], ["ASPECTS", count(data?.aspects)]].map(([label, value]) => <div key={String(label)} className="border border-[#102936]/15 bg-white/60 p-5"><p className="font-mono text-[9px] tracking-[.14em] text-[#B63C5E]">{label}</p><p className="mt-3 font-serif text-4xl">{value}</p></div>)}</div>
      {pattern && <article className="relative overflow-hidden border border-[#211B2A] bg-[#211B2A] p-7 text-[#F3F0E9] shadow-[-8px_9px_0_#EF5D3F] md:p-9"><span className="absolute right-6 top-6 font-mono text-[8px] tracking-[.14em] text-[#E1A0B1]">P-04 / PATTERN READING</span><p className="flex items-center gap-2 font-mono text-[9px] font-semibold tracking-[.15em] text-[#E1A0B1]"><Sparkles size={13} /> YOUR IN-DEPTH PATTERN</p><h2 className="mt-5 max-w-2xl font-serif text-4xl leading-[.92] tracking-[-.05em] md:text-5xl">{pattern.headline}</h2><p className="mt-5 max-w-2xl font-sans text-[14px] leading-6 text-[#D9D1EF]">{pattern.overview}</p><div className="mt-8 grid gap-px bg-white/15 md:grid-cols-2">{pattern.dimensions.map(item => <div key={item.label} className="bg-[#211B2A] p-5"><p className="font-mono text-[8px] tracking-[.14em] text-[#E1A0B1]">{item.label}</p><h3 className="mt-3 font-serif text-2xl leading-none">{item.title}</h3><p className="mt-4 font-sans text-[13px] leading-6 text-[#D9D1EF]">{item.interpretation}</p></div>)}</div><Link href="/daily-ritual" className="mt-8 inline-flex items-center gap-2 font-mono text-[9px] font-semibold tracking-[.14em] text-white hover:text-[#E1A0B1]">OPEN TODAY’S PATTERN PRACTICE <ArrowUpRight size={14} /></Link></article>}
      <details className="border border-[#102936]/15 bg-white/60 p-6"><summary className="cursor-pointer list-none font-mono text-[10px] font-semibold tracking-[.14em]"><span className="inline-flex items-center gap-2"><BookOpen size={14} className="text-[#B63C5E]" /> CALCULATION NOTES</span></summary><div className="mt-5 border-t border-[#102936]/10 pt-5 font-sans text-[14px] leading-7 text-[#55707d]"><p>Your chart is calculated from the birth date, time, and place you saved to your private profile. It includes planet placements, houses, and major aspects; the written reading is a reflective interpretation of those calculated inputs.</p><p className="mt-4">The pattern reading and daily teaching are generated on demand from those calculated fields. Cosmic does not present these tools as a diagnosis, guarantee, or substitute for professional advice.</p></div></details></div> : <div className="mt-10 border border-[#102936]/15 bg-white/60 p-7"><p className="font-serif text-3xl">No calculated chart yet.</p><p className="mt-3 font-sans text-[14px] leading-6 text-[#55707d]">Create your profile and choose Calculate My Chart from the natal section when you are ready.</p><Link href="/" className="mt-6 inline-block font-mono text-[10px] tracking-[.14em] text-[#B63C5E]">RETURN TO YOUR HOME →</Link></div>}
  </section></main>;
}
