import { BookmarkCheck, ChevronRight } from "lucide-react";
import { useEffect } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { SaveForLaterButton } from "@/components/SaveForLaterButton";
import { trpc } from "@/lib/trpc";

export default function SavedItems() {
  const { isAuthenticated, loading } = useAuth();
  const savedQuery = trpc.cosmic.listSavedItems.useQuery(undefined, { enabled: isAuthenticated });
  useEffect(() => { if (!loading && !isAuthenticated) window.location.href = "/account"; }, [isAuthenticated, loading]);
  if (loading || !isAuthenticated) return <main className="flex min-h-screen items-center justify-center bg-[#F3F0E9] px-5"><p className="font-mono text-[10px] tracking-[.14em] text-[#55707d]">OPENING YOUR SAVED COSMIC INDEX…</p></main>;
  return <main className="min-h-screen bg-[#F3F0E9] px-5 py-7 text-[#102936] md:px-9 md:py-10"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between border-b border-[#102936]/10 pb-5"><Link href="/" className="font-mono text-[9px] tracking-[.14em] text-[#55707d] hover:text-[#EF5D3F]">← COSMIC WISDOM</Link><p className="font-mono text-[8px] tracking-[.14em] text-[#EF5D3F]">PRIVATE SAVED INDEX</p></header><section className="mt-14 grid gap-10 md:grid-cols-[.72fr_1.28fr]"><div><p className="font-mono text-[9px] font-semibold tracking-[.15em] text-[#EF5D3F]">SAVED FOR LATER</p><h1 className="mt-5 font-serif text-5xl leading-[.88] tracking-[-.06em] md:text-6xl">Keep the threads<br /><em className="font-light text-[#B63C5E]">you want to return to.</em></h1><p className="mt-6 max-w-sm font-sans text-[15px] leading-7 text-[#55707d]">Your saved Cosmic Wisdom content is visible only to your member account.</p></div><div>{savedQuery.isLoading ? <div className="border border-[#102936]/15 bg-white/45 p-8 font-mono text-[10px] tracking-[.14em] text-[#55707d]">LOADING YOUR INDEX…</div> : savedQuery.data?.length ? <div className="grid gap-3">{savedQuery.data.map(item => <article key={item.id} className="border border-[#102936]/15 bg-white/45 p-6"><div className="flex items-start justify-between gap-4"><div><p className="font-mono text-[8px] tracking-[.14em] text-[#EF5D3F]">{item.contentType.replaceAll("_", " ").toUpperCase()}</p><h2 className="mt-3 font-serif text-3xl leading-none">{item.title}</h2><p className="mt-3 max-w-xl font-sans text-[13px] leading-6 text-[#55707d]">{item.summary}</p></div><BookmarkCheck size={17} className="shrink-0 text-[#EF5D3F]" /></div><div className="mt-6 flex items-center justify-between border-t border-[#102936]/10 pt-4"><Link href={item.href} className="inline-flex items-center gap-1 font-mono text-[8px] tracking-[.13em] text-[#102936] hover:text-[#EF5D3F]">OPEN <ChevronRight size={13} /></Link><SaveForLaterButton item={item} /></div></article>)}</div> : <div className="border border-[#102936]/15 bg-white/45 p-8"><BookmarkCheck size={20} className="text-[#EF5D3F]" /><h2 className="mt-5 font-serif text-3xl leading-none">Nothing saved yet.</h2><p className="mt-4 max-w-md font-sans text-[14px] leading-6 text-[#55707d]">Use Save for later on a Cosmic lens or today’s field note to build a private return list.</p><Link href="/" className="mt-7 inline-flex font-mono text-[9px] tracking-[.14em] text-[#EF5D3F] hover:text-[#B63C5E]">EXPLORE COSMIC WISDOM →</Link></div>}</div></section></div></main>;
}
